CREATE DATABASE Senatur_Tarde

USE Senatur_Tarde

CREATE TABLE Pacotes (
IdPacote		INT PRIMARY KEY IDENTITY
,NomePacote		VARCHAR(255) NOT NULL
,Descricao		TEXT NOT NULL
,DataIda		DATE NOT NULL 
,DataVolta		DATE NOT NULL
,Valor			DECIMAl (9,2) NOT NULL
,NomeCidade		VARCHAR (255) NOT NULL
,Ativo			BIT NOT NULL
);

CREATE TABLE TiposUsuarios (
IdTipoUsuario		INT PRIMARY KEY IDENTITY
,Titulo				VARCHAR (255) NOT NULL
);

CREATE TABLE Usuarios (
IdUsuario		INT PRIMARY KEY IDENTITY
,Email			VARCHAR (255) NOT NULL UNIQUE
,Senha			VARCHAR (255) NOT NULL
,IdTipoUsuario	INT FOREIGN KEY REFERENCES TiposUsuarios (IdTipoUsuario) 
);

